# faster builds on new travis setup not using sudo
sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:      
  fast_finish: true
  allow_failures:
    - php: nightly

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

script:
  # validate composer.json
  - composer validate
  # run PHPUnit
  - vendor/bin/phpunit --verbose --coverage-text

